org: ipj31
app: zargons-domain
service: resources
frameworkVersion: "3"

provider:
  name: aws
  region: us-east-2

resources:
  Resources:
    SessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage, self:provider.stage}-sessions
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    # This table is used to store user connections
    Connections:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:app}-${opt:stage, self:provider.stage}-user-connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # This table is used to store temporary passwords for WebSocket connections
    WebSocketPreflightTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:app}-${opt:stage, self:provider.stage}-websocket-preflight
        AttributeDefinitions:
          - AttributeName: tempPassword
            AttributeType: S
        KeySchema:
          - AttributeName: tempPassword
            KeyType: HASH
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttl
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
