org: ipj31
app: zargons-domain
service: zargon-api
frameworkVersion: "3"

provider:
  name: aws
  region: us-east-2
  runtime: python3.11
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

package:
  individually: true
  exclude:
    - "**/**"

functions:
  create-session:
    handler: create_session.handler
    package:
      include:
        - create_session.py
    events:
      - httpApi:
          path: /session
          method: post
          authorizer:
            type: aws_iam
  select-hero:
    handler: select_hero.handler
    package:
      include:
        - select_hero.py
    events:
      - httpApi:
          path: /session/{sessionId}/select
          method: put
          authorizer:
            type: aws_iam
  start-session:
    handler: start_session.handler
    package:
      include:
        - start_session.py
    events:
      - httpApi:
          path: /session/{sessionId}
          method: post
          authorizer:
            type: aws_iam
  close-session:
    handler: close_session.handler
    package:
      include:
        - close_session.py
    events:
      - httpApi:
          path: /session/{sessionId}/close
          method: put
          authorizer:
            type: aws_iam
  update-hero:
    handler: update_hero.handler
    package:
      include:
        - update_hero.py
    events:
      - httpApi:
          path: /session/{sessionId}/updateHero/{heroType}
          method: put
          authorizer:
            type: aws_iam

  get-sessions:
    handler: get_sessions.handler
    package:
      include:
        - get_sessions.py
    events:
      - httpApi:
          path: /session
          method: get
          authorizer:
            type: aws_iam

  join-session:
    handler: join_session.handler
    package:
      include:
        - join_session.py
    events:
      - httpApi:
          path: /session/join
          method: put
          authorizer:
            type: aws_iam

  delete-session:
    handler: delete_session.handler
    package:
      include:
        - delete_session.py
    events:
      - httpApi:
          path: /session/{sessionId}
          method: delete
          authorizer:
            type: aws_iam
